### ISSUE TITLE
Ratings do not show open for title cards where progress bar is shown

### ISSUE THREAD

**Issue by nitinsurana** [tanner-rutgers/RateFlix#1]
Videos already watched, shows a progress bar instead of meta. 
![progress_bar_missing_ratings](https://user-images.githubusercontent.com/7137160/37544757-800fee6e-293c-11e8-8278-361a4acb5fb1.png)
as can be seen in the above image.

**Comment by nitinsurana** [comment]
https://github.com/tanner-rutgers/RateFlix/pull/2 fixes this issue.

**Comment by tanner-rutgers** [comment]
Fixed by https://github.com/tanner-rutgers/RateFlix/pull/2
